spring.application.name=Crud_Project

spring.datasource.url=jdbc:mysql://localhost:3306/teacher_record_db

spring.datasource.username=root
spring.datasource.password=UJJAWAL123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


